---

stages:
  - unit_test
  - static_analysis
  - pypi

unit_test:
  stage: unit_test
  image: registry.gitlab.com/aw1cks/docker-tox:latest
  only:
    - tags
  script:
    - tox

static_analysis:
  stage: static_analysis
  image: docker.io/kiwicom/mypy:latest
  only:
    - tags
  script:
    - mypy src

pypi:
  stage: pypi
  image: docker.io/python:latest
  only:
    - tags
  script:
    - pip install --upgrade build setuptools twine
    - python -m build
    # Upload to GitLab package registry
    - >-
      TWINE_PASSWORD="${CI_JOB_TOKEN}"
      TWINE_USERNAME='gitlab-ci-token'
      TWINE_REPOSITORY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
      twine upload --verbose dist/*
    # Upload to PyPi
    - >-
      TWINE_PASSWORD="${PYPI_TOKEN}"
      TWINE_USERNAME='__token__'
      twine upload --verbose dist/*
